CREATE DATABASE IF NOT EXISTS banco;

USE banco;

CREATE TABLE clientes(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    sobrenome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    endereco VARCHAR(255) NOT NULL,
    cidade VARCHAR(255) NOT NULL,
    estado VARCHAR(255) NOT NULL,
    cep VARCHAR(255) NOT NULL
);


CREATE TABLE corretor(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(70) NOT NULL,
    cpf VARCHAR(15) NOT NULL,
    telefone VARCHAR(30) NOT NULL,
    email VARCHAR(80) NOT NULL,
    localidade VARCHAR(255) NOT NULL
);
